apiVersion: v1
kind: Service
metadata:
  name: qwen14b-service
  namespace: project
  labels:
    app: qwen14b-serving
spec:
  type: NodePort
  selector:
    app: qwen14b-serving
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30090
